baseURL: https://www.bacula-web.org/
languageCode: en-us
title: Bacula-Web
theme: ananke

enableRobotsTXT: true
SectionPagesMenu: "main"
Paginate: "6"

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

menu:
  main:
  - identifier: Documentations
    name: Docs
    url: https://docs.bacula-web.org

params:
  favicon: "favicon.ico"
  site_logo: "/bacula-web-logo.png"
  description: "Open source web based reporting and monitoring tool for Bacula"
  rss: "index.xml"
  github: "https://github.com/bacula-web/bacula-web"
  featured_image: "bacula-web-dashboard.png"
